<?php
$translate = $this->plugin('translate');
$twitter = "https://twitter.com/intent/tweet?url=".$url."&text=".$title;
$facebook= "https://www.facebook.com/sharer/sharer.php?u=".$url;
$pocket= "http://getpocket.com/edit?url=".$url;
$line="http://line.me/R/msg/text/?".$url;
$mail="mailto:?body=".$url;
?>

<table>
    <tr>
        <th width="20%"><?php echo $translate('Citation'); ?></th>
        <td><span id="citing"></span> <input style="margin-left : 10px;" type="button" value="<?php echo $translate('Copy'); ?>" onclick="copy()"/></td>
    </tr>
    <tr>
        <th><?php echo $translate('JSON-LD'); ?></th>
        <td><a href="<?php echo $uri; ?>"><?php echo $uri; ?></a></td>
    </tr>
    <tr>
        <th><?php echo $translate('Share'); ?></th>
        <td>
            <a href="<?php echo $twitter; ?>" title="Twitter" target="_blank">Twitter</a> /
            <a href="<?php echo $facebook; ?>" title="Facebook" target="_blank">Facebook</a> /
            <a href="<?php echo $pocket; ?>" title="Pocket" target="_blank">Pocket</a></li> /
            <a href="<?php echo $line; ?>" title="Line" target="_blank">Line</a></li> /
            <a href="<?php echo $mail; ?>" title="Mail">Mail</a></li>
        </td>
    </tr>
</table>

<script>
    let title = "<?php echo $title; ?>";
    let url = "<?php echo $url; ?>";

    //記載例
    let text = `${title}\n(${url})`
    document.getElementById('citing').textContent = text;

    async function copy(){
        var listener = function(e){

            e.clipboardData.setData("text/plain" , text);    
            // 本来のイベントをキャンセル
            e.preventDefault();
            // 終わったら一応削除
            document.removeEventListener("copy", listener);
        }

        // コピーのイベントが発生したときに、クリップボードに書き込むようにしておく
        document.addEventListener("copy" , listener);

        // コピー
        document.execCommand("copy");
        alert("<?php echo $translate('Copied'); ?>")
    }
</script>